### ISSUE TITLE
Automatic style checker

### ISSUE THREAD

**Issue by bartq** [johnpapa/angular-styleguide#293] opened 2015-02-27 14:28 UTC
Is there a tool that allows checking of this style automatically? If not, would it be interesting for you?

**Comment by johnpapa** [comment] 2015-02-27 14:53
yep. i'd like a jscs-angular based on my guide. just havent had time

**Comment by johnpapa** [comment] 2015-02-27 15:28
similar thread #207

**Comment by johnpapa** [comment] 2015-03-05 06:56
dupe of #194

**Closed by johnpapa** 2015-03-05 06:56 UTC
Labels: help wanted
